typography_spectrum: 0.27760049421340227
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7290445878170431
  lightness: 0.5216936480719596
  saturation: 0.1403542305342853
  rhythmicContrast: 0.6601873440667987
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.246594492578879
analytics: {}
author:
  name: Playa Escondida Lodge
  url: ''
  email: playaescondidalodge@gmail.com
name: 'Escondida Lodge, Costa Rica'
cta: {}
navigation:
  - name: the beach Lodge
    id: eb4e4436-c5b9-4cae-9e48-b75fe4126bad
    type: content
title: ''
coverPrefs:
  filter: false
purpose: []
