name: Escondida Lodge
favicon: null
layout_spectrum: 0.24331
typography_spectrum: 0.05640232306905091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d13'
    - '#605c59'
    - '#2dd4fe'
    - '#4187ba'
    - '#d8deb0'
  brandStrength: 0.8895800535101444
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
