layout_spectrum: 0.06323667545802891
typography_spectrum: 0.27760049421340227
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7290445878170431
  lightness: 0.5216936480719596
  saturation: 0.1403542305342853
  rhythmicContrast: 0.6601873440667987
name: 'Escondida Lodge, Costa Rica'
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose: []
title: ''
author:
  name: Playa Escondida Lodge
  url: ''
  email: playaescondidalodge@gmail.com
content_rating:
  adult: false
