name: Escondida Lodge
favicon: null
layout_spectrum: 0.49045
typography_spectrum: 0.05640232306905091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#363636'
    - '#888888'
    - '#b3b3b3'
    - '#e9e9e9'
  brandStrength: 0.8895800535101444
  lightness: 0.0012582240160554647
  saturation: 0.8042590587865561
  rhythmicContrast: 0.5
purpose: []
